### ISSUE TITLE
Script panics with "missing field `is_deleted`" on downloading a pool

### ISSUE THREAD

**Issue by head-gardener** [McSib/e621_downloader#60]
Running the script with auto-generated config and tags.txt stripped down to a single default pool:
```
[pools]
1106 # Title: Taste of the Order
```
Yields following error:
```
[07:08 $]> RUST_BACKTRACE=1 ./e621_downloader
Should enter safe mode? no
04:09:29 [ERROR] Could not convert entry to type "e621_downloader::e621::sender::entries::PoolEntry"!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `is_deleted`", line: 0, column: 0)

   0: failure::backtrace::internal::InternalBacktrace::new
   1: failure::backtrace::Backtrace::new
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
   3: <core::result::Result<T,E> as failure::result_ext::ResultExt<T,E>>::with_context
   4: e621_downloader::e621::sender::RequestSender::get_entry_from_appended_id
   5: e621_downloader::e621::grabber::Grabber::grab_posts_by_tags
   6: e621_downloader::program::Program::run
   7: e621_downloader::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1.61.0/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/1.61.0/library/std/src/panicking.rs:492
      std::panicking::try
             at /rustc/1.61.0/library/std/src/panicking.rs:456
      std::panic::catch_unwind
             at /rustc/1.61.0/library/std/src/panic.rs:137
      std::rt::lang_start_internal::{{closure}}
             at /rustc/1.61.0/library/std/src/rt.rs:128
      std::panicking::try::do_call
             at /rustc/1.61.0/library/std/src/panicking.rs:492
      std::panicking::try
             at /rustc/1.61.0/library/std/src/panicking.rs:456
      std::panic::catch_unwind
             at /rustc/1.61.0/library/std/src/panic.rs:137
      std::rt::lang_start_internal
             at /rustc/1.61.0/library/std/src/rt.rs:128
  11: main
  12: <unknown>
  13: __libc_start_main
  14: _start


missing field `is_deleted`', src/e621/sender/mod.rs:295:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.61.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1.61.0/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/1.61.0/library/core/src/result.rs:1785:5
   3: e621_downloader::e621::sender::RequestSender::get_entry_from_appended_id
   4: e621_downloader::e621::grabber::Grabber::grab_posts_by_tags
   5: e621_downloader::program::Program::run
   6: e621_downloader::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Full logs:
[e621_downloader.log](https://github.com/McSib/e621_downloader/files/10009101/e621_downloader.log)

Other groups download flawlessly.

**Comment by head-gardener** [comment]
As per [e621 API reference](https://e621.net/help/api#pools) pools no longer supply `is_deleted`. Furthermore, the field is never referenced in the script. I propose deleting the field entirely.
